#!/usr/bin/env bash

# Ask system password
sudo echo "Please type password before running the script"

# Symbolic link with .dotfiles to ~/$HOME directory
find "$(pwd)" -name ".*" -type f -maxdepth 1 | xargs -I '{}' ln -s '{}' ~

# Install the CLI tools for Xcode
xcode-select --install

# Install Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install formulas
brew install ansible
brew install awscli
brew install direnv
brew install docker docker-compose docke-machine
brew install ffmpeg
brew install git
brew install graphicsmagick
brew install graphviz
brew install httpie
brew install imagemagick
brew install mysql
brew install redis
brew install postgresql
brew install pstree
brew install tfenv
brew install tree
brew install webkit2png
brew install webpack
brew install wget
brew install wifi-password
brew tap heroku/brew && brew install heroku
brew tap thoughtbot/formulae && brew install parity

# Install iterm & configuration
brew cask install iterm2
cp iterm/profile.json ~/Library/Application\ Support/iTerm2/DynamicProfiles/profile.json

# Install zsh & oh-my-zsh configuration
brew install zsh zsh-completions
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
upgrade_oh_my_zsh

# iTerm2: Install Shell Integration
curl -L https://iterm2.com/shell_integration/install_shell_integration.sh | bash

brew install rbenv ruby-build
$ eval "$(rbenv init -)"

brew install nodenv
$ eval "$(nodenv init -)"

# cask
brew cask install 1password
brew cask install alfred
brew cask install brave-browser
brew cask install caffeine
brew cask install dash
brew cask install docker
brew cask install evernote
brew cask install google-chrome
brew cask install google-drive
brew cask install imageoptim
brew cask install kap
brew cask install kodi
brew cask install openemu
brew cask install postico
brew cask install postman
brew cask install session-manager-plugin
brew cask install slack
brew cask install sourcetree
brew cask install spotify
brew cask install tor-browser
brew cask install virtualbox
brew cask install visual-studio-code
brew cask install vlc
brew tap homebrew/cask && brew cask install chromedriver

# Install Spectacle & configuration
brew cask install spectacle
cp spectacle/shortcuts.json ~/Library/Application\ Support/Spectacle/Shortcuts.json

# Install Atom & configuration
brew cask install atom
find "$(pwd)" -name "atom" -type d | xargs -I '{}' ln -s '{}' ~/.atom
apm install package-sync

# Change screenshots format
defaults write com.apple.screencapture type jpg
mkdir ~/Pictures/Screenshots/
defaults write com.apple.screencapture location ~/Pictures/Screenshots

# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Show battery life percentage.
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

# Adds more icons on menu bar
defaults write com.apple.systemuiserver menuExtras -array \
  "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" \
  "/System/Library/CoreServices/Menu Extras/AirPort.menu" \
  "/System/Library/CoreServices/Menu Extras/Battery.menu" \
  "/System/Library/CoreServices/Menu Extras/Clock.menu" \
  "/System/Library/CoreServices/Menu Extras/User.menu" \
  "/System/Library/CoreServices/Menu Extras/Volume.menu"

defaults write com.apple.systemuiserver "NSStatusItem Visible Siri" -bool false
defaults write com.apple.systemuiserver "NSStatusItem Visible com.apple.menuextra.airport" -bool true
defaults write com.apple.systemuiserver "NSStatusItem Visible com.apple.menuextra.appleuser" -bool true
defaults write com.apple.systemuiserver "NSStatusItem Visible com.apple.menuextra.battery" -bool true
defaults write com.apple.systemuiserver "NSStatusItem Visible com.apple.menuextra.bluetooth" -bool true
defaults write com.apple.systemuiserver "NSStatusItem Visible com.apple.menuextra.volume" -bool true

# Set the value of the IsAnalog key to false so that the digital clock is displayed
defaults write com.apple.menuextra.clock IsAnalog -bool false

# Set the date and time format to display Thu 18 Aug 23:46
defaults write com.apple.menuextra.clock DateFormat -string "EEE d MMM HH:mm" && killall SystemUIServer

# Set dock tilesize
defaults write com.apple.dock tilesize -int 15 && killall Dock

# Set dock magnification
defaults write com.apple.dock magnification -bool true

# Set dock largesize maximum
defaults write com.apple.dock largesize -int 100

# Autohide dock
defaults write com.apple.dock autohide -bool true

# Show Hidden Files
defaults write com.apple.finder AppleShowAllFiles YES

# Install all available software updates
sudo softwareupdate -ia
