#!/usr/bin/env bash

# Ask system password
sudo echo "Please type password before running the script"

# Symbolic link with .dotfiles to ~/$HOME directory
find "$(pwd)" -name ".*" -type f -maxdepth 1 | xargs -I '{}' ln -s '{}' ~

# Install the CLI tools for Xcode
xcode-select --install

# Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install formulas
brew install ansible
brew install awscli
brew install direnv
brew install docker docker-compose docke-machine
brew install ffmpeg
brew install git
brew install graphicsmagick
brew install graphviz
brew install httpie
brew install imagemagick
brew install mysql
brew install redis
brew install postgresql
brew install pstree
brew install tfenv
brew install tree
brew install webkit2png
brew install webpack
brew install wget
brew install wifi-password
brew tap heroku/brew && brew install heroku
brew tap thoughtbot/formulae && brew install parity

# Install iterm & configuration
brew install --cask iterm2
cp iterm/profile.json ~/Library/Application\ Support/iTerm2/DynamicProfiles/profile.json

# Install zsh & oh-my-zsh configuration
brew install zsh zsh-completions
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# iTerm2: Install Shell Integration
curl -L https://iterm2.at/install_shell_integration.sh | bash

brew install rbenv
rbenv init

brew install nodenv
$ eval "$(nodenv init -)"

# cask
brew install --cask 1password
brew install --cask alfred
brew install --cask brave-browser
brew install --cask caffeine
brew install --cask chromedriver
brew install --cask dash
brew install --cask docker
brew install --cask evernote
brew install --cask google-chrome
brew install --cask google-drive
brew install --cask imageoptim
brew install --cask kap
brew install --cask keka
brew install --cask kodi
brew install --cask microsoft-teams
brew install --cask openemu
brew install --cask postico
brew install --cask postman
brew install --cask session-manager-plugin
brew install --cask shazam
brew install --cask slack
brew install --cask sourcetree
brew install --cask spotify
brew install --cask tor-browser
brew install --cask virtualbox
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask zoom

# Install Spectacle & configuration
brew install --cask spectacle
cp spectacle/shortcuts.json ~/Library/Application\ Support/Spectacle/Shortcuts.json

# Install Atom & configuration
brew install --cask atom
find "$(pwd)" -name "atom" -type d | xargs -I '{}' ln -s '{}' ~/.atom
apm install package-sync

# Change screenshots format
defaults write com.apple.screencapture type jpg
mkdir ~/Pictures/Screenshots/
defaults write com.apple.screencapture location ~/Pictures/Screenshots

# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Show battery life percentage.
defaults write ~/Library/Preferences/ByHost/com.apple.controlcenter.plist BatteryShowPercentage -bool true

# Adds more icons on menu bar
defaults write com.apple.systemuiserver menuExtras -array \
  "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" \
  "/System/Library/CoreServices/Menu Extras/AirPort.menu" \
  "/System/Library/CoreServices/Menu Extras/Battery.menu" \
  "/System/Library/CoreServices/Menu Extras/Clock.menu" \
  "/System/Library/CoreServices/Menu Extras/User.menu" \
  "/System/Library/CoreServices/Menu Extras/Volume.menu"

defaults write com.apple.systemuiserver "NSStatusItem Visible Siri" -bool false
defaults write com.apple.systemuiserver "NSStatusItem Visible com.apple.menuextra.airport" -bool true
defaults write com.apple.systemuiserver "NSStatusItem Visible com.apple.menuextra.appleuser" -bool true
defaults write com.apple.systemuiserver "NSStatusItem Visible com.apple.menuextra.battery" -bool true
defaults write com.apple.systemuiserver "NSStatusItem Visible com.apple.menuextra.bluetooth" -bool true
defaults write com.apple.systemuiserver "NSStatusItem Visible com.apple.menuextra.volume" -bool true

# Quit System Preferences
killall System\ Preferences > /dev/null 2>&1

# Set the value of the IsAnalog key to false so that the digital clock is displayed
defaults write com.apple.menuextra.clock.plist IsAnalog -bool false

# Set the date and time format to display Thu 18 Aug 23:46
defaults write com.apple.menuextra.clock.plist DateFormat -string "EEE d MMM HH:mm"

# Set the various keys based upon the new format string
# Day (Thu)
defaults write com.apple.menuextra.clock.plist ShowDayOfWeek -bool true
# Date (18 Aug)
defaults write com.apple.menuextra.clock.plist ShowDayOfMonth -bool true
# 24-hour time (23:46)
defaults delete -g AppleICUForce12HourTime > /dev/null 2>&1\n
defaults write com.apple.menuextra.clock.plist Show24Hour -bool true

# Restart the ControlCenter process for changes to take effect
killall ControlCenter

# Set dock tilesize
defaults write com.apple.dock tilesize -int 35 && killall Dock

# Set dock magnification
defaults write com.apple.dock magnification -bool true

# Set dock largesize maximum
defaults write com.apple.dock largesize -int 100

# Autohide dock
defaults write com.apple.dock autohide -bool true

# Show Hidden Files
defaults write com.apple.Finder "AppleShowAllFiles" -bool "true" && killall Finder

# Install all available software updates
sudo softwareupdate -ia
