#!/bin/sh

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
NC='\033[0m'

# Check if rubocop is installed for the current project
rubocop -v >/dev/null 2>&1 || { echo >&2 "${red}[Ruby Style][Fatal]: Add rubocop to your Gemfile"; exit 1; }

# Get only the staged files
FILES=$(git status -uno -s | sed s/^...// | grep -v "db/schema.rb\|Gemfile.lock" | tr '\n' ' ')

echo $FILES

echo "${green}[Ruby Style][Info]: Checking Ruby Style${NC}"

if [ -n "$FILES" ]
then
  echo "${green}[Ruby Style][Info]:\n ${FILES}${NC}"
  if [ ! -f '.rubocop.yml' ]; then
    echo "${yellow}[Ruby Style][Warning]: No .rubocop.yml config file.${NC}"
  fi

  # Run rubocop on the staged files
  bin/bundle exec rubocop ${FILES}

  if [ $? -ne 0 ]; then
    echo "${red}[Ruby Style][Error]: Fix the issues and commit again${NC}"
    exit 1
  fi
else
  echo "${green}[Ruby Style][Info]: No files to check${NC}"
fi

exit 0
